# SwiftLint Configuration for SwiftMoLogger
# Based on Swift best practices and iOS development standards

# Include these paths in linting
included:
  - Sources
  - Tests

# Exclude these paths from linting
excluded:
  - .build
  - .swiftpm
  - Package.swift

# Enable these rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disable these rules
disabled_rules:
  - todo # Allow TODO comments for development

# Configure specific rules
line_length:
  warning: 120
  error: 140

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - ok

type_name:
  min_length: 3
  max_length:
    warning: 45
    error: 50

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3

# File-specific configurations
custom_rules:
  # Ensure proper logging usage
  no_print_statements:
    name: "No Print Statements"
    regex: 'print\('
    message: "Use SwiftMoLogger instead of print statements"
    severity: warning
    
  # Ensure proper force unwrapping usage
  force_unwrapping_warning:
    name: "Force Unwrapping Warning"
    regex: '\w+!'
    message: "Consider using optional binding or nil-coalescing operator"
    severity: warning
    
  # Ensure proper TODO format
  todo_format:
    name: "TODO Format"
    regex: '(?i)todo(?!:)'
    message: "TODO should be followed by colon and description: TODO: description"
    severity: warning

# Specific rules for logging framework
opening_brace:
  allow_multiline_func: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

closure_parameter_position:
  severity: error

comma:
  severity: error

control_statement:
  severity: error

empty_parentheses_with_trailing_closure:
  severity: warning

force_cast:
  severity: error

force_try:
  severity: error

implicit_getter:
  severity: warning

leading_whitespace:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

operator_whitespace:
  severity: error

return_arrow_whitespace:
  severity: error

statement_position:
  severity: error

trailing_newline:
  severity: error

trailing_semicolon:
  severity: error

valid_ibinspectable:
  severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"